procergs_notification_service_Notification:
    type: rest
    prefix: /v1
    resource: "@PROCERGSNotificationServiceBundle/Controller/NotificationController.php"
    name_prefix: api_1_

procergs_notification_service_User:
    type: rest
    prefix: /v1
    resource: "@PROCERGSNotificationServiceBundle/Controller/UserController.php"
    name_prefix: api_1_

procergs_notification_service_Sender:
    type: rest
    parent: procergs_notification_service_User
    resource: "@PROCERGSNotificationServiceBundle/Controller/SenderController.php"
    name_prefix: api_1_