security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER, ROLE_API_V1, ROLE_GET_NOTIFICATION, ROLE_LIST_NOTIFICATIONS ]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

#        wsse_secured:
#            pattern:   ^/api
#            stateless: true
#            wsse:      { lifetime: 30 }

        secured_area:
            pattern:    ^/api/v1
            stateless:  true
            simple_preauth:
                authenticator: apikey_authenticator

    access_control:
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/v1, roles: ROLE_API_V1 }
